spring.application.name=JobManager
spring.datasource.url=jdbc:h2:mem:RoadToSDE3
spring.datasource.driverClassName:org.h2.Driver
spring.datasource.username=SDE3
spring.datasource.password=
spring.jpa.show-sql=True
spring.jpa.properties.hibernate.format_sql=True
